## Load the libraries

In [1]:
import pandas as pd

In [4]:
train = pd.read_csv("train.csv")

In [5]:
train

,Transaction_ID,Transaction_Date,Store_ID,Number_of_EMI,Purchased_in_Sale,Var1,Var2,Var3,Client_ID,Gender,DOB,Referred_Friend,Sales_Executive_ID,Sales_Executive_Category,Lead_Source_Category,Payment_Mode,Product_Category,Transaction_Amount
0,TRA98825550,1-Jan-03,STO1281,2,N,1,1,1,345821599,F,19-Aug-71,NO,SD23011859,B,Advertisment,Credit/Debit Card,Cat A,17455
1,TRA98825710,1-Jan-03,STO1247,2,N,1,2,1,345821734,M,3-Jul-76,NO,SD23000293,B,Advertisment,Credit/Debit Card,Cat A,16503
2,TRA98823874,1-Jan-03,STO1244,2,N,1,1,1,345820365,F,4-Jan-59,NO,SD23011768,B,Advertisment,Credit/Debit Card,Cat A,15012
3,TRA98823889,1-Jan-03,STO1256,2,N,1,1,1,345820377,M,11-May-60,NO,SD23011691,B,Advertisment,Credit/Debit Card,Cat A,16051
4,TRA98824521,1-Jan-03,STO1445,2,N,1,2,1,345820841,F,24-Mar-62,NO,SD23003031,B,Reference,Cheque,Cat A,15108
5,TRA98824747,1-Jan-03,STO1233,2,N,1,1,1,345821008,M,11-Sep-75,NO,SD23011684,B,Advertisment,Cash,Cat A,17292
6,TRA98826034,1-Jan-03,STO1314,2,N,1,2,1,345821979,F,9-May-66,NO,SD23021263,B,Advertisment,Credit/Debit Card,Cat A,16982
7,TRA98825775,1-Jan-03,STO1243,2,N,1,2,1,345821781,M,19-Dec-57,YES,SD23012337,B,Advertisment,Credit/Debit Card,Cat A,20093
8,TRA98823882,1-Jan-03,STO1250,2,N,1,2,1,345820371,M,8-Aug-62,NO,SD23011854,B,Advertisment,Credit/Debit Card,Cat A,15495
9,TRA98824721,1-Jan-03,STO1291,2,N,1,1,1,345820984,M,21-Jan-81,YES,SD23011738,B,Advertisment,Cheque,Cat A,16592
10,TRA98826564,1-Jan-03,STO1264,2,N,1,1,1,345671632,M,21-Feb-62,NO,SD23011704,A,Walkin,Credit/Debit Card,Cat A,19794
11,TRA98824571,1-Jan-03,STO1250,2,N,1,2,1,345820877,F,4-Jun-63,NO,SD23011854,B,Advertisment,Credit/Debit Card,Cat A,19588
12,TRA98823911,1-Jan-03,STO1255,2,N,1,2,1,345820393,F,23-Oct-69,NO,SD23000253,B,Advertisment,Credit/Debit Card,Cat A,17738
13,TRA98823921,1-Jan-03,STO1244,2,N,1,2,1,345820404,M,4-Jan-79,NO,SD23001988,B,Advertisment,Credit/Debit Card,Cat A,19275
14,TRA98826182,1-Jan-03,STO1260,2,N,1,2,1,345822091,M,6-Jan-68,NO,SD23000212,B,Advertisment,Credit/Debit Card,Cat A,20241
15,TRA98824717,1-Jan-03,STO1260,2,N,1,2,1,345820982,F,6-Jan-56,NO,SD23000856,A,Walkin,Credit/Debit Card,Cat A,21527
16,TRA98826059,1-Jan-03,STO1304,2,N,1,1,1,345821997,M,20-Nov-66,NO,SD23001958,B,Advertisment,Credit/Debit Card,Cat A,22987
17,TRA98826007,1-Jan-03,STO1247,2,N,1,2,1,345821962,M,4-Jan-64,NO,SD23000656,B,Advertisment,Credit/Debit Card,Cat A,20278
18,TRA98824107,1-Jan-03,STO1233,2,N,1,1,1,345820541,M,27-Jul-81,NO,SD23011684,B,Advertisment,Cheque,Cat B,19200
19,TRA98826696,1-Jan-03,STO1233,2,N,1,1,1,345822478,F,20-Sep-81,NO,SD23011684,B,Advertisment,Credit/Debit Card,Cat B,22800
20,TRA98825254,1-Jan-03,STO1247,2,N,1,1,1,345821383,F,23-Apr-81,NO,SD23000452,B,Advertisment,Credit/Debit Card,Cat B,18000
21,TRA98825479,1-Jan-03,STO1390,2,N,1,2,1,345821546,M,5-Jun-81,YES,SD23011818,B,Advertisment,Cash,Cat B,23400
22,TRA98824294,1-Jan-03,STO1304,2,N,1,1,1,345820678,M,28-Sep-81,YES,SD23012027,B,Advertisment,Cash,Cat B,18600
23,TRA98824244,1-Jan-03,STO1247,2,N,1,2,1,345820646,M,2-Nov-80,NO,SD23000452,B,Advertisment,Credit/Debit Card,Cat B,18600
24,TRA98824399,1-Jan-03,STO1250,2,N,1,1,1,345744302,M,14-May-80,NO,SD23001459,A,Walkin,Credit/Debit Card,Cat B,23400
25,TRA98825677,1-Jan-03,STO1264,2,N,1,1,1,345821705,M,5-Jul-80,NO,SD23000157,C,Other,Credit/Debit Card,Cat B,18600
26,TRA98825858,1-Jan-03,STO1264,2,N,1,1,1,345821844,M,5-Jan-81,NO,SD23000187,B,Advertisment,Credit/Debit Card,Cat B,19200
27,TRA98823820,1-Jan-03,STO1277,2,N,1,1,1,345820329,F,28-Apr-80,NO,SD23011688,B,Advertisment,Cheque,Cat B,23400
28,TRA98824887,1-Jan-03,STO1256,2,N,1,1,1,345821114,M,9-Dec-80,NO,SD23011691,B,Advertisment,Credit/Debit Card,Cat B,22800
29,TRA98825500,1-Jan-03,STO1271,2,N,1,2,1,345821562,M,12-Sep-79,YES,SD23012264,B,Advertisment,Cheque,Cat B,18000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439511,TRA100022248,30-Dec-06,STO1651,2,N,1,2,1,346663646,M,6-Jul-85,NO,SD23084332,A,Walkin,Credit/Debit Card,Cat H,24667
439512,TRA100022267,30-Dec-06,STO1346,2,N,1,1,1,346663663,F,11-Dec-75,YES,SD23086527,A,Walkin,Cheque,Cat H,26858
439513,TRA100022207,30-Dec-06,STO1244,3,N,1,1,1,346663620,F,6-Jan-58,NO,SD23083705,A,Walkin,Credit/Debit Card,Cat H,26425
439514,TRA100022318,30-Dec-06,STO1691,2,N,1,2,2,346663698,F,6-Jan-76,NO,SD23083608,A,Walkin,Credit/Debit Card,Cat H,32738
439515,TRA100022212,30-Dec-06,STO1682,2,N,1,2,2,346663623,M,8-May-79,NO,SD23065327,A,Walkin,Credit/Debit Card,Cat H,31314
439516,TRA100022249,30-Dec-06,STO1691,3,N,1,1,2,346663647,M,5-Jan-82,NO,SD23059386,A,Walkin,Credit/Debit Card,Cat H,38520
439517,TRA100022282,30-Dec-06,STO1663,3,N,1,1,2,346663674,F,4-Jan-84,NO,SD23045779,A,Walkin,Credit/Debit Card,Cat H,38477
439518,TRA100022387,30-Dec-06,STO1292,2,N,1,1,1,346663734,M,7-Mar-80,YES,SD23089166,A,Walkin,Credit/Debit Card,Cat H,33660
439519,TRA100022313,30-Dec-06,STO1287,2,N,1,2,1,346661936,M,16-Dec-45,NO,SD23084503,C,Advertisment,Cheque,Cat H,32301
439520,TRA100022241,30-Dec-06,STO1651,3,N,1,2,1,346663642,M,13-Jan-70,NO,SD23076476,A,Walkin,Credit/Debit Card,Cat H,45357
439521,TRA100022276,30-Dec-06,STO1321,2,N,1,1,1,346663671,F,4-Jan-79,NO,SD23000219,B,Advertisment,Credit/Debit Card,Cat H,53051
439522,TRA100022341,30-Dec-06,STO1260,1,Y,2,1,1,346663712,F,3-Sep-64,NO,SD23003782,A,Walkin,Cheque,Cat H,73652
439523,TRA100022393,30-Dec-06,STO1231,2,N,1,1,1,346663740,M,6-Feb-53,NO,SD23089085,D,Advertisment,Cheque,Cat H,66545
439524,TRA100022256,30-Dec-06,STO1244,2,N,1,1,1,346663653,M,4-Jan-59,NO,SD23000969,B,Advertisment,Credit/Debit Card,Cat H,83339
439525,TRA100022258,30-Dec-06,STO1316,2,N,1,1,1,346663654,M,11-Oct-77,NO,SD23058567,A,Walkin,Credit/Debit Card,Cat H,77887
439526,TRA100022271,30-Dec-06,STO1264,2,N,1,1,1,346663667,M,11-Jun-85,NO,SD23001313,B,Advertisment,Credit/Debit Card,Cat H,92059
439527,TRA100022270,30-Dec-06,STO1412,8,N,3,1,1,346663665,M,15-Oct-75,NO,SD23072973,A,Walkin,NaN,Cat H,93933
439528,TRA100022342,30-Dec-06,STO1281,2,N,1,1,2,346663713,M,14-Jan-81,NO,SD23055601,B,Advertisment,Credit/Debit Card,Cat H,387644
439529,TRA100022420,31-Dec-06,STO1247,2,N,1,1,1,346663761,M,14-Mar-67,YES,SD23082123,A,Advertisment,Cheque,Cat H,20795
439530,TRA100022574,31-Dec-06,STO1663,2,N,1,1,1,346273922,M,6-Jan-63,NO,SD23049973,A,Walkin,Cheque,Cat H,25867
439531,TRA100022550,31-Dec-06,STO1247,2,N,1,1,1,346611861,M,5-Feb-67,NO,SD23088389,A,Advertisment,Cheque,Cat H,29900
439532,TRA100022476,31-Dec-06,STO1246,2,N,1,1,1,346663799,F,17-Dec-66,NO,SD23017843,A,Walkin,Cheque,Cat H,28619
439533,TRA100022553,31-Dec-06,STO1247,2,N,1,1,1,346663850,F,10-Jun-58,NO,SD23079671,A,Advertisment,Cheque,Cat H,34891
439534,TRA100022620,31-Dec-06,STO1390,3,N,3,2,1,346663894,M,5-Dec-59,NO,SD23083854,A,Walkin,NaN,Cat H,31072
439535,TRA100022466,31-Dec-06,STO1663,2,N,1,1,1,346663789,F,7-Mar-63,NO,SD23083654,A,Walkin,Credit/Debit Card,Cat H,33535
439536,TRA100022485,31-Dec-06,STO1281,2,N,1,1,1,346663807,M,4-Jan-84,NO,SD23000466,B,Advertisment,Credit/Debit Card,Cat H,32563
439537,TRA100022502,31-Dec-06,STO1373,2,N,3,1,1,346663820,M,15-Jun-58,YES,SD23089175,A,Walkin,Cheque,Cat H,56706
439538,TRA100022551,31-Dec-06,STO1346,2,N,1,2,1,346663849,F,11-Jan-55,NO,SD23055874,B,Advertisment,Credit/Debit Card,Cat H,184254
439539,TRA100022443,31-Dec-06,STO1695,2,N,1,1,1,346663777,F,5-Jan-78,NO,SD23080146,A,Walkin,Credit/Debit Card,Cat H,271404
439540,TRA100022501,31-Dec-06,STO1281,2,N,1,1,1,346663818,M,14-Jan-73,NO,SD23000217,B,Advertisment,Credit/Debit Card,Cat H,332406

In [6]:
train.apply(lambda x: sum(x.isnull()))

Transaction_ID                  0
Transaction_Date                0
Store_ID                        0
Number_of_EMI                   0
Purchased_in_Sale               0
Var1                            0
Var2                            0
Var3                            0
Client_ID                       0
Gender                          0
DOB                             0
Referred_Friend                 7
Sales_Executive_ID              0
Sales_Executive_Category        0
Lead_Source_Category            0
Payment_Mode                14513
Product_Category                0
Transaction_Amount              0
dtype: int64

In [10]:
train['Client_ID'].value_counts()

345629580    19
345724132    19
346234361    19
346021065    18
345913383    17
346100533    16
345709003    15
346008305    14
346159301    14
345844309    14
345841935    14
345871358    14
346432633    13
345643174    13
345988144    13
345967973    12
346488684    12
345710365    11
346316621    11
346220609    11
346078203    11
346219677    11
345856079    11
345676356    10
346167074    10
345951552    10
346231732    10
345855099    10
346181588    10
345919529    10
             ..
346099568     1
346097521     1
346101619     1
346107764     1
346105717     1
346255164     1
346249019     1
346236725     1
346191647     1
346224399     1
346165008     1
346167059     1
346173204     1
346177302     1
346179353     1
346183451     1
346189596     1
346187549     1
346263328     1
346238772     1
346261281     1
346265379     1
346275622     1
346283818     1
346289967     1
346230576     1
346228529     1
346234674     1
346232627     1
346038276     1
Name: Client_ID, dtype: int64

In [12]:
train.dtypes

Transaction_ID              object
Transaction_Date            object
Store_ID                    object
Number_of_EMI                int64
Purchased_in_Sale           object
Var1                         int64
Var2                         int64
Var3                         int64
Client_ID                    int64
Gender                      object
DOB                         object
Referred_Friend             object
Sales_Executive_ID          object
Sales_Executive_Category    object
Lead_Source_Category        object
Payment_Mode                object
Product_Category            object
Transaction_Amount           int64
dtype: object