## Analytics Vidhaya Loan Prediction

In [81]:
import pandas as pd
import graphlab as gl

In [82]:
#loans = pd.read_csv('train_u6lujuX.csv')
loans = gl.SFrame('train_u6lujuX.csv')

Finished parsing file C:\Users\ranjank\data\mywork\github\av\competitions\loan-prediction\train_u6lujuX.csv

Parsing completed. Parsed 100 lines in 0.03002 secs.

Finished parsing file C:\Users\ranjank\data\mywork\github\av\competitions\loan-prediction\train_u6lujuX.csv

Parsing completed. Parsed 614 lines in 0.033024 secs.

------------------------------------------------------
Inferred types from first line of file as
column_type_hints=[str,str,str,str,str,str,long,long,long,long,long,str,str]
If parsing fails due to incorrect types, you can correct
the inferred type list above and pass it to read_csv in
the column_type_hints argument
------------------------------------------------------

In [83]:
loans

Columns:
	Loan_ID	str
	Gender	str
	Married	str
	Dependents	str
	Education	str
	Self_Employed	str
	ApplicantIncome	int
	CoapplicantIncome	int
	LoanAmount	int
	Loan_Amount_Term	int
	Credit_History	int
	Property_Area	str
	Loan_Status	str

Rows: 614

Data:
+----------+--------+---------+------------+--------------+---------------+
| Loan_ID  | Gender | Married | Dependents |  Education   | Self_Employed |
+----------+--------+---------+------------+--------------+---------------+
| LP001002 |  Male  |    No   |     0      |   Graduate   |       No      |
| LP001003 |  Male  |   Yes   |     1      |   Graduate   |       No      |
| LP001005 |  Male  |   Yes   |     0      |   Graduate   |      Yes      |
| LP001006 |  Male  |   Yes   |     0      | Not Graduate |       No      |
| LP001008 |  Male  |    No   |     0      |   Graduate   |       No      |
| LP001011 |  Male  |   Yes   |     2      |   Graduate   |      Yes      |
| LP001013 |  Male  |   Yes   |     0      | Not Graduate |       No      |
| LP001014 |  Male  |   Yes   |     3+     |   Graduate   |       No      |
| LP001018 |  Male  |   Yes   |     2      |   Graduate   |       No      |
| LP001020 |  Male  |   Yes   |     1      |   Graduate   |       No      |
+----------+--------+---------+------------+--------------+---------------+
+-----------------+-------------------+------------+------------------+----------------+
| ApplicantIncome | CoapplicantIncome | LoanAmount | Loan_Amount_Term | Credit_History |
+-----------------+-------------------+------------+------------------+----------------+
|       5849      |         0         |    None    |       360        |       1        |
|       4583      |        1508       |    128     |       360        |       1        |
|       3000      |         0         |     66     |       360        |       1        |
|       2583      |        2358       |    120     |       360        |       1        |
|       6000      |         0         |    141     |       360        |       1        |
|       5417      |        4196       |    267     |       360        |       1        |
|       2333      |        1516       |     95     |       360        |       1        |
|       3036      |        2504       |    158     |       360        |       0        |
|       4006      |        1526       |    168     |       360        |       1        |
|      12841      |       10968       |    349     |       360        |       1        |
+-----------------+-------------------+------------+------------------+----------------+
+---------------+-------------+
| Property_Area | Loan_Status |
+---------------+-------------+
|     Urban     |      Y      |
|     Rural     |      N      |
|     Urban     |      Y      |
|     Urban     |      Y      |
|     Urban     |      Y      |
|     Urban     |      Y      |
|     Urban     |      Y      |
|   Semiurban   |      N      |
|     Urban     |      Y      |
|   Semiurban   |      N      |
+---------------+-------------+
[614 rows x 13 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [84]:
features = ['Gender',              
            'Married',               
            'Dependents',     
            'Education', 
            'Self_Employed', 
            'ApplicantIncome',
            'CoapplicantIncome',
            'LoanAmount',
            'Loan_Amount_Term',
            'Credit_History',
            'Property_Area'
           ]
loans['safe_loans'] = loans['Loan_Status'].apply(lambda x : +1 if x=='Y' else -1)
loans.remove_column('Loan_Status')
target = 'safe_loans'
loans = loans[features + [target]]

In [85]:
loans

Columns:
	Gender	str
	Married	str
	Dependents	str
	Education	str
	Self_Employed	str
	ApplicantIncome	int
	CoapplicantIncome	int
	LoanAmount	int
	Loan_Amount_Term	int
	Credit_History	int
	Property_Area	str
	safe_loans	int

Rows: 614

Data:
+--------+---------+------------+--------------+---------------+-----------------+
| Gender | Married | Dependents |  Education   | Self_Employed | ApplicantIncome |
+--------+---------+------------+--------------+---------------+-----------------+
|  Male  |    No   |     0      |   Graduate   |       No      |       5849      |
|  Male  |   Yes   |     1      |   Graduate   |       No      |       4583      |
|  Male  |   Yes   |     0      |   Graduate   |      Yes      |       3000      |
|  Male  |   Yes   |     0      | Not Graduate |       No      |       2583      |
|  Male  |    No   |     0      |   Graduate   |       No      |       6000      |
|  Male  |   Yes   |     2      |   Graduate   |      Yes      |       5417      |
|  Male  |   Yes   |     0      | Not Graduate |       No      |       2333      |
|  Male  |   Yes   |     3+     |   Graduate   |       No      |       3036      |
|  Male  |   Yes   |     2      |   Graduate   |       No      |       4006      |
|  Male  |   Yes   |     1      |   Graduate   |       No      |      12841      |
+--------+---------+------------+--------------+---------------+-----------------+
+-------------------+------------+------------------+----------------+---------------+
| CoapplicantIncome | LoanAmount | Loan_Amount_Term | Credit_History | Property_Area |
+-------------------+------------+------------------+----------------+---------------+
|         0         |    None    |       360        |       1        |     Urban     |
|        1508       |    128     |       360        |       1        |     Rural     |
|         0         |     66     |       360        |       1        |     Urban     |
|        2358       |    120     |       360        |       1        |     Urban     |
|         0         |    141     |       360        |       1        |     Urban     |
|        4196       |    267     |       360        |       1        |     Urban     |
|        1516       |     95     |       360        |       1        |     Urban     |
|        2504       |    158     |       360        |       0        |   Semiurban   |
|        1526       |    168     |       360        |       1        |     Urban     |
|       10968       |    349     |       360        |       1        |   Semiurban   |
+-------------------+------------+------------------+----------------+---------------+
+------------+
| safe_loans |
+------------+
|     1      |
|     -1     |
|     1      |
|     1      |
|     1      |
|     1      |
|     1      |
|     -1     |
|     1      |
|     -1     |
+------------+
[614 rows x 12 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [86]:
print "Total loan applications: ", len(loans)
print "No. of missing gender info: ", len(loans) - (len(loans[loans['Gender'] == 'Male']) + len(loans[loans['Gender'] == 'Female']))
len(loans[loans['Gender'] == ''])

Total loan applications:  614
No. of missing gender info:  13

13

### Balancing data

In [87]:
safe_loans_raw = loans[loans[target] == 1]
risky_loans_raw = loans[loans[target] == -1]

# Undersample the safe loans.
percentage = len(risky_loans_raw)/float(len(safe_loans_raw))
risky_loans = risky_loans_raw
safe_loans = safe_loans_raw.sample(percentage, seed=1)
loans_data = risky_loans_raw.append(safe_loans)

print "Percentage of safe loans                 :", len(safe_loans) / float(len(loans_data))
print "Percentage of risky loans                :", len(risky_loans) / float(len(loans_data))
print "Total number of loans in our new dataset :", len(loans_data)

Percentage of safe loans                 : 0.5
Percentage of risky loans                : 0.5
Total number of loans in our new dataset : 384

In [88]:
for feature in features:
    loans_data_one_hot_encoded = loans_data[feature].apply(lambda x: {x: 1})    
    loans_data_unpacked = loans_data_one_hot_encoded.unpack(column_name_prefix=feature)
    
    # Change None's to 0's
    for column in loans_data_unpacked.column_names():
        loans_data_unpacked[column] = loans_data_unpacked[column].fillna(0)

    loans_data.remove_column(feature)
    loans_data.add_columns(loans_data_unpacked)

In [89]:
features = loans_data.column_names()
features.remove('safe_loans')  # Remove the response variable
features

['Gender.',
 'Gender.Female',
 'Gender.Male',
 'Married.',
 'Married.No',
 'Married.Yes',
 'Dependents.',
 'Dependents.0',
 'Dependents.1',
 'Dependents.2',
 'Dependents.3+',
 'Education.Graduate',
 'Education.Not Graduate',
 'Self_Employed.',
 'Self_Employed.No',
 'Self_Employed.Yes',
 'ApplicantIncome.150',
 'ApplicantIncome.210',
 'ApplicantIncome.416',
 'ApplicantIncome.645',
 'ApplicantIncome.674',
 'ApplicantIncome.1000',
 'ApplicantIncome.1299',
 'ApplicantIncome.1378',
 'ApplicantIncome.1442',
 'ApplicantIncome.1500',
 'ApplicantIncome.1600',
 'ApplicantIncome.1668',
 'ApplicantIncome.1759',
 'ApplicantIncome.1800',
 'ApplicantIncome.1811',
 'ApplicantIncome.1828',
 'ApplicantIncome.1830',
 'ApplicantIncome.1836',
 'ApplicantIncome.1853',
 'ApplicantIncome.1880',
 'ApplicantIncome.1907',
 'ApplicantIncome.1916',
 'ApplicantIncome.1963',
 'ApplicantIncome.1977',
 'ApplicantIncome.2000',
 'ApplicantIncome.2014',
 'ApplicantIncome.2045',
 'ApplicantIncome.2071',
 'ApplicantIncome.2083',
 'ApplicantIncome.2130',
 'ApplicantIncome.2138',
 'ApplicantIncome.2149',
 'ApplicantIncome.2165',
 'ApplicantIncome.2167',
 'ApplicantIncome.2178',
 'ApplicantIncome.2192',
 'ApplicantIncome.2213',
 'ApplicantIncome.2214',
 'ApplicantIncome.2221',
 'ApplicantIncome.2237',
 'ApplicantIncome.2239',
 'ApplicantIncome.2275',
 'ApplicantIncome.2281',
 'ApplicantIncome.2301',
 'ApplicantIncome.2309',
 'ApplicantIncome.2333',
 'ApplicantIncome.2346',
 'ApplicantIncome.2378',
 'ApplicantIncome.2383',
 'ApplicantIncome.2400',
 'ApplicantIncome.2423',
 'ApplicantIncome.2435',
 'ApplicantIncome.2454',
 'ApplicantIncome.2473',
 'ApplicantIncome.2483',
 'ApplicantIncome.2492',
 'ApplicantIncome.2500',
 'ApplicantIncome.2507',
 'ApplicantIncome.2510',
 'ApplicantIncome.2583',
 'ApplicantIncome.2600',
 'ApplicantIncome.2609',
 'ApplicantIncome.2620',
 'ApplicantIncome.2625',
 'ApplicantIncome.2645',
 'ApplicantIncome.2647',
 'ApplicantIncome.2653',
 'ApplicantIncome.2666',
 'ApplicantIncome.2667',
 'ApplicantIncome.2679',
 'ApplicantIncome.2698',
 'ApplicantIncome.2708',
 'ApplicantIncome.2718',
 'ApplicantIncome.2720',
 'ApplicantIncome.2726',
 'ApplicantIncome.2755',
 'ApplicantIncome.2769',
 'ApplicantIncome.2785',
 'ApplicantIncome.2787',
 'ApplicantIncome.2873',
 'ApplicantIncome.2876',
 'ApplicantIncome.2889',
 'ApplicantIncome.2917',
 'ApplicantIncome.2927',
 'ApplicantIncome.2947',
 'ApplicantIncome.2957',
 'ApplicantIncome.2958',
 'ApplicantIncome.2980',
 'ApplicantIncome.2987',
 'ApplicantIncome.3000',
 'ApplicantIncome.3010',
 'ApplicantIncome.3015',
 'ApplicantIncome.3017',
 'ApplicantIncome.3029',
 'ApplicantIncome.3033',
 'ApplicantIncome.3036',
 'ApplicantIncome.3052',
 'ApplicantIncome.3062',
 'ApplicantIncome.3069',
 'ApplicantIncome.3074',
 'ApplicantIncome.3083',
 'ApplicantIncome.3087',
 'ApplicantIncome.3089',
 'ApplicantIncome.3095',
 'ApplicantIncome.3103',
 'ApplicantIncome.3125',
 'ApplicantIncome.3159',
 'ApplicantIncome.3166',
 'ApplicantIncome.3167',
 'ApplicantIncome.3180',
 'ApplicantIncome.3200',
 'ApplicantIncome.3229',
 'ApplicantIncome.3232',
 'ApplicantIncome.3237',
 'ApplicantIncome.3250',
 'ApplicantIncome.3254',
 'ApplicantIncome.3326',
 'ApplicantIncome.3333',
 'ApplicantIncome.3340',
 'ApplicantIncome.3357',
 'ApplicantIncome.3358',
 'ApplicantIncome.3365',
 'ApplicantIncome.3366',
 'ApplicantIncome.3399',
 'ApplicantIncome.3400',
 'ApplicantIncome.3406',
 'ApplicantIncome.3417',
 'ApplicantIncome.3418',
 'ApplicantIncome.3427',
 'ApplicantIncome.3430',
 'ApplicantIncome.3459',
 'ApplicantIncome.3466',
 'ApplicantIncome.3481',
 'ApplicantIncome.3497',
 'ApplicantIncome.3500',
 'ApplicantIncome.3510',
 'ApplicantIncome.3522',
 'ApplicantIncome.3523',
 'ApplicantIncome.3539',
 'ApplicantIncome.3541',
 'ApplicantIncome.3547',
 'ApplicantIncome.3572',
 'ApplicantIncome.3583',
 'ApplicantIncome.3588',
 'ApplicantIncome.3593',
 'ApplicantIncome.3596',
 'ApplicantIncome.3597',
 'ApplicantIncome.3598',
 'ApplicantIncome.3600',
 'ApplicantIncome.3617',
 'ApplicantIncome.3620',
 'ApplicantIncome.3625',
 'ApplicantIncome.3652',
 'ApplicantIncome.3660',
 'ApplicantIncome.3667',
 'ApplicantIncome.3675',
 'ApplicantIncome.3676',
 'ApplicantIncome.3691',
 'ApplicantIncome.3708',
 'ApplicantIncome.3716',
 'ApplicantIncome.3717',
 'ApplicantIncome.3748',
 'ApplicantIncome.3750',
 'ApplicantIncome.3762',
 'ApplicantIncome.3800',
 'ApplicantIncome.3812',
 'ApplicantIncome.3813',
 'ApplicantIncome.3814',
 'ApplicantIncome.3833',
 'ApplicantIncome.3846',
 'ApplicantIncome.3858',
 'ApplicantIncome.3865',
 'ApplicantIncome.3867',
 'ApplicantIncome.3875',
 'ApplicantIncome.3887',
 'ApplicantIncome.3900',
 'ApplicantIncome.3902',
 'ApplicantIncome.3917',
 'ApplicantIncome.3948',
 'ApplicantIncome.3975',
 'ApplicantIncome.3987',
 'ApplicantIncome.3992',
 'ApplicantIncome.4000',
 'ApplicantIncome.4009',
 'ApplicantIncome.4050',
 'ApplicantIncome.4053',
 'ApplicantIncome.4095',
 'ApplicantIncome.4100',
 'ApplicantIncome.4166',
 'ApplicantIncome.4200',
 'ApplicantIncome.4226',
 'ApplicantIncome.4230',
 'ApplicantIncome.4281',
 'ApplicantIncome.4283',
 'ApplicantIncome.4300',
 'ApplicantIncome.4310',
 'ApplicantIncome.4333',
 'ApplicantIncome.4342',
 'ApplicantIncome.4344',
 'ApplicantIncome.4350',
 'ApplicantIncome.4384',
 'ApplicantIncome.4400',
 'ApplicantIncome.4408',
 'ApplicantIncome.4416',
 'ApplicantIncome.4547',
 'ApplicantIncome.4554',
 'ApplicantIncome.4566',
 'ApplicantIncome.4583',
 'ApplicantIncome.4606',
 'ApplicantIncome.4616',
 'ApplicantIncome.4625',
 'ApplicantIncome.4652',
 'ApplicantIncome.4666',
 'ApplicantIncome.4680',
 'ApplicantIncome.4683',
 'ApplicantIncome.4691',
 'ApplicantIncome.4692',
 'ApplicantIncome.4707',
 'ApplicantIncome.4723',
 'ApplicantIncome.4735',
 'ApplicantIncome.4755',
 'ApplicantIncome.4758',
 'ApplicantIncome.4843',
 'ApplicantIncome.4865',
 'ApplicantIncome.4887',
 'ApplicantIncome.4895',
 'ApplicantIncome.4917',
 'ApplicantIncome.4931',
 'ApplicantIncome.4945',
 'ApplicantIncome.4950',
 'ApplicantIncome.5000',
 'ApplicantIncome.5042',
 'ApplicantIncome.5116',
 'ApplicantIncome.5124',
 'ApplicantIncome.5166',
 'ApplicantIncome.5185',
 'ApplicantIncome.5191',
 'ApplicantIncome.5250',
 'ApplicantIncome.5266',
 'ApplicantIncome.5285',
 'ApplicantIncome.5316',
 'ApplicantIncome.5417',
 'ApplicantIncome.5488',
 'ApplicantIncome.5500',
 'ApplicantIncome.5503',
 'ApplicantIncome.5516',
 'ApplicantIncome.5568',
 'ApplicantIncome.5677',
 'ApplicantIncome.5695',
 'ApplicantIncome.5726',
 'ApplicantIncome.5746',
 'ApplicantIncome.5815',
 'ApplicantIncome.5829',
 'ApplicantIncome.5923',
 'ApplicantIncome.5935',
 'ApplicantIncome.6000',
 'ApplicantIncome.6033',
 'ApplicantIncome.6045',
 'ApplicantIncome.6050',
 'ApplicantIncome.6065',
 'ApplicantIncome.6080',
 'ApplicantIncome.6096',
 'ApplicantIncome.6125',
 'ApplicantIncome.6216',
 'ApplicantIncome.6250',
 'ApplicantIncome.6277',
 'ApplicantIncome.6283',
 'ApplicantIncome.6333',
 'ApplicantIncome.6383',
 'ApplicantIncome.6400',
 'ApplicantIncome.6406',
 'ApplicantIncome.6417',
 'ApplicantIncome.6500',
 'ApplicantIncome.6608',
 'ApplicantIncome.6633',
 'ApplicantIncome.6782',
 'ApplicantIncome.7100',
 'ApplicantIncome.7167',
 'ApplicantIncome.7250',
 'ApplicantIncome.7333',
 'ApplicantIncome.7441',
 'ApplicantIncome.7583',
 'ApplicantIncome.7660',
 'ApplicantIncome.7933',
 'ApplicantIncome.8000',
 'ApplicantIncome.8072',
 'ApplicantIncome.8300',
 'ApplicantIncome.8333',
 'ApplicantIncome.8334',
 'ApplicantIncome.8624',
 'ApplicantIncome.8666',
 'ApplicantIncome.8750',
 'ApplicantIncome.8799',
 'ApplicantIncome.9166',
 'ApplicantIncome.9167',
 'ApplicantIncome.9323',
 'ApplicantIncome.9357',
 'ApplicantIncome.9560',
 'ApplicantIncome.9833',
 'ApplicantIncome.10000',
 'ApplicantIncome.10047',
 'ApplicantIncome.10139',
 'ApplicantIncome.10408',
 'ApplicantIncome.10416',
 'ApplicantIncome.10513',
 'ApplicantIncome.10750',
 'ApplicantIncome.11000',
 'ApplicantIncome.11250',
 'ApplicantIncome.11417',
 'ApplicantIncome.11500',
 'ApplicantIncome.11757',
 'ApplicantIncome.12000',
 'ApplicantIncome.12500',
 'ApplicantIncome.12841',
 'ApplicantIncome.12876',
 'ApplicantIncome.13650',
 'ApplicantIncome.14583',
 'ApplicantIncome.14683',
 'ApplicantIncome.14866',
 'ApplicantIncome.14880',
 'ApplicantIncome.14999',
 'ApplicantIncome.16120',
 'ApplicantIncome.16250',
 'ApplicantIncome.16667',
 'ApplicantIncome.17263',
 'ApplicantIncome.17500',
 'ApplicantIncome.18333',
 'ApplicantIncome.19730',
 'ApplicantIncome.20233',
 'ApplicantIncome.20667',
 'ApplicantIncome.23803',
 'ApplicantIncome.33846',
 'ApplicantIncome.37719',
 'ApplicantIncome.81000',
 'CoapplicantIncome.0',
 'CoapplicantIncome.189',
 'CoapplicantIncome.240',
 'CoapplicantIncome.242',
 'CoapplicantIncome.461',
 'CoapplicantIncome.505',
 'CoapplicantIncome.536',
 'CoapplicantIncome.663',
 'CoapplicantIncome.736',
 'CoapplicantIncome.754',
 'CoapplicantIncome.913',
 'CoapplicantIncome.985',
 'CoapplicantIncome.997',
 'CoapplicantIncome.1000',
 'CoapplicantIncome.1030',
 'CoapplicantIncome.1040',
 'CoapplicantIncome.1086',
 'CoapplicantIncome.1126',
 'CoapplicantIncome.1167',
 'CoapplicantIncome.1210',
 'CoapplicantIncome.1229',
 'CoapplicantIncome.1250',
 'CoapplicantIncome.1255',
 'CoapplicantIncome.1280',
 'CoapplicantIncome.1287',
 'CoapplicantIncome.1300',
 'CoapplicantIncome.1302',
 'CoapplicantIncome.1330',
 'CoapplicantIncome.1376',
 'CoapplicantIncome.1398',
 'CoapplicantIncome.1411',
 'CoapplicantIncome.1424',
 'CoapplicantIncome.1430',
 'CoapplicantIncome.1451',
 'CoapplicantIncome.1459',
 'CoapplicantIncome.1483',
 'CoapplicantIncome.1500',
 'CoapplicantIncome.1508',
 'CoapplicantIncome.1542',
 'CoapplicantIncome.1560',
 'CoapplicantIncome.1587',
 'CoapplicantIncome.1600',
 'CoapplicantIncome.1603',
 'CoapplicantIncome.1619',
 'CoapplicantIncome.1625',
 'CoapplicantIncome.1640',
 'CoapplicantIncome.1664',
 'CoapplicantIncome.1666',
 'CoapplicantIncome.1667',
 'CoapplicantIncome.1668',
 'CoapplicantIncome.1695',
 'CoapplicantIncome.1710',
 'CoapplicantIncome.1717',
 'CoapplicantIncome.1733',
 'CoapplicantIncome.1742',
 'CoapplicantIncome.1750',
 'CoapplicantIncome.1774',
 'CoapplicantIncome.1793',
 'CoapplicantIncome.1800',
 'CoapplicantIncome.1811',
 'CoapplicantIncome.1833',
 'CoapplicantIncome.1843',
 'CoapplicantIncome.1863',
 'CoapplicantIncome.1872',
 'CoapplicantIncome.1881',
 'CoapplicantIncome.1911',
 'CoapplicantIncome.1915',
 'CoapplicantIncome.1917',
 'CoapplicantIncome.1950',
 'CoapplicantIncome.1964',
 'CoapplicantIncome.1983',
 'CoapplicantIncome.1987',
 'CoapplicantIncome.1993',
 'CoapplicantIncome.2004',
 'CoapplicantIncome.2014',
 'CoapplicantIncome.2016',
 'CoapplicantIncome.2034',
 'CoapplicantIncome.2054',
 'CoapplicantIncome.2064',
 'CoapplicantIncome.2067',
 'CoapplicantIncome.2083',
 'CoapplicantIncome.2087',
 'CoapplicantIncome.2100',
 'CoapplicantIncome.2115',
 'CoapplicantIncome.2138',
 'CoapplicantIncome.2142',
 'CoapplicantIncome.2157',
 'CoapplicantIncome.2166',
 'CoapplicantIncome.2167',
 'CoapplicantIncome.2168',
 'CoapplicantIncome.2188',
 'CoapplicantIncome.2200',
 'CoapplicantIncome.2210',
 'CoapplicantIncome.2223',
 'CoapplicantIncome.2250',
 'CoapplicantIncome.2254',
 'CoapplicantIncome.2283',
 'CoapplicantIncome.2330',
 'CoapplicantIncome.2333',
 'CoapplicantIncome.2365',
 'CoapplicantIncome.2375',
 'CoapplicantIncome.2383',
 'CoapplicantIncome.2400',
 'CoapplicantIncome.2405',
 'CoapplicantIncome.2426',
 'CoapplicantIncome.2451',
 'CoapplicantIncome.2466',
 'CoapplicantIncome.2500',
 'CoapplicantIncome.2504',
 'CoapplicantIncome.2524',
 'CoapplicantIncome.2531',
 'CoapplicantIncome.2541',
 'CoapplicantIncome.2569',
 'CoapplicantIncome.2583',
 'CoapplicantIncome.2669',
 'CoapplicantIncome.2739',
 'CoapplicantIncome.2840',
 'CoapplicantIncome.2857',
 'CoapplicantIncome.2859',
 'CoapplicantIncome.2900',
 'CoapplicantIncome.2917',
 'CoapplicantIncome.2925',
 'CoapplicantIncome.2934',
 'CoapplicantIncome.3000',
 'CoapplicantIncome.3022',
 'CoapplicantIncome.3136',
 'CoapplicantIncome.3150',
 'CoapplicantIncome.3230',
 'CoapplicantIncome.3237',
 'CoapplicantIncome.3334',
 'CoapplicantIncome.3369',
 'CoapplicantIncome.3428',
 'CoapplicantIncome.3440',
 'CoapplicantIncome.3447',
 'CoapplicantIncome.3449',
 'CoapplicantIncome.3500',
 'CoapplicantIncome.3541',
 'CoapplicantIncome.3600',
 'CoapplicantIncome.3666',
 'CoapplicantIncome.3683',
 'CoapplicantIncome.3750',
 'CoapplicantIncome.3800',
 'CoapplicantIncome.3806',
 'CoapplicantIncome.3850',
 'CoapplicantIncome.3890',
 'CoapplicantIncome.4000',
 'CoapplicantIncome.4114',
 'CoapplicantIncome.4167',
 'CoapplicantIncome.4266',
 'CoapplicantIncome.4301',
 'CoapplicantIncome.4333',
 'CoapplicantIncome.4416',
 'CoapplicantIncome.4417',
 'CoapplicantIncome.4490',
 'CoapplicantIncome.4583',
 'CoapplicantIncome.4595',
 'CoapplicantIncome.4750',
 'CoapplicantIncome.4983',
 'CoapplicantIncome.4996',
 'CoapplicantIncome.5063',
 'CoapplicantIncome.5064',
 'CoapplicantIncome.5266',
 'CoapplicantIncome.5296',
 'CoapplicantIncome.5302',
 'CoapplicantIncome.5624',
 'CoapplicantIncome.5625',
 'CoapplicantIncome.6250',
 'CoapplicantIncome.6666',
 'CoapplicantIncome.7210',
 'CoapplicantIncome.7250',
 'CoapplicantIncome.7750',
 'CoapplicantIncome.8333',
 'CoapplicantIncome.10968',
 'CoapplicantIncome.11300',
 'CoapplicantIncome.20000',
 'CoapplicantIncome.33837',
 'CoapplicantIncome.41667',
 'LoanAmount.9',
 'LoanAmount.17',
 'LoanAmount.25',
 'LoanAmount.30',
 'LoanAmount.35',
 'LoanAmount.36',
 'LoanAmount.42',
 'LoanAmount.44',
 'LoanAmount.45',
 'LoanAmount.46',
 'LoanAmount.50',
 'LoanAmount.53',
 'LoanAmount.54',
 'LoanAmount.55',
 'LoanAmount.56',
 'LoanAmount.58',
 'LoanAmount.60',
 'LoanAmount.61',
 'LoanAmount.62',
 'LoanAmount.63',
 'LoanAmount.65',
 'LoanAmount.66',
 'LoanAmount.67',
 'LoanAmount.70',
 'LoanAmount.71',
 'LoanAmount.72',
 'LoanAmount.74',
 'LoanAmount.75',
 'LoanAmount.76',
 'LoanAmount.78',
 'LoanAmount.80',
 'LoanAmount.81',
 'LoanAmount.83',
 'LoanAmount.84',
 'LoanAmount.85',
 'LoanAmount.86',
 'LoanAmount.87',
 'LoanAmount.88',
 'LoanAmount.90',
 'LoanAmount.93',
 'LoanAmount.94',
 'LoanAmount.95',
 'LoanAmount.96',
 'LoanAmount.97',
 'LoanAmount.98',
 'LoanAmount.99',
 'LoanAmount.100',
 'LoanAmount.101',
 'LoanAmount.102',
 'LoanAmount.103',
 'LoanAmount.104',
 'LoanAmount.105',
 'LoanAmount.106',
 'LoanAmount.107',
 'LoanAmount.108',
 'LoanAmount.109',
 'LoanAmount.110',
 'LoanAmount.111',
 'LoanAmount.112',
 'LoanAmount.113',
 'LoanAmount.114',
 'LoanAmount.115',
 'LoanAmount.116',
 'LoanAmount.117',
 'LoanAmount.118',
 'LoanAmount.119',
 'LoanAmount.120',
 'LoanAmount.121',
 'LoanAmount.122',
 'LoanAmount.123',
 'LoanAmount.124',
 'LoanAmount.125',
 'LoanAmount.126',
 'LoanAmount.127',
 'LoanAmount.128',
 'LoanAmount.129',
 'LoanAmount.130',
 'LoanAmount.131',
 'LoanAmount.132',
 'LoanAmount.133',
 'LoanAmount.134',
 'LoanAmount.135',
 'LoanAmount.136',
 'LoanAmount.137',
 'LoanAmount.138',
 'LoanAmount.140',
 'LoanAmount.141',
 'LoanAmount.143',
 'LoanAmount.144',
 'LoanAmount.146',
 'LoanAmount.148',
 'LoanAmount.149',
 'LoanAmount.150',
 'LoanAmount.151',
 'LoanAmount.152',
 'LoanAmount.153',
 'LoanAmount.154',
 'LoanAmount.155',
 'LoanAmount.157',
 'LoanAmount.158',
 'LoanAmount.159',
 'LoanAmount.160',
 'LoanAmount.161',
 'LoanAmount.162',
 'LoanAmount.164',
 'LoanAmount.165',
 'LoanAmount.167',
 'LoanAmount.168',
 'LoanAmount.170',
 'LoanAmount.172',
 'LoanAmount.173',
 'LoanAmount.175',
 'LoanAmount.176',
 'LoanAmount.178',
 'LoanAmount.180',
 'LoanAmount.181',
 'LoanAmount.182',
 'LoanAmount.184',
 'LoanAmount.185',
 'LoanAmount.186',
 'LoanAmount.187',
 'LoanAmount.190',
 'LoanAmount.191',
 'LoanAmount.192',
 'LoanAmount.194',
 'LoanAmount.196',
 'LoanAmount.200',
 'LoanAmount.201',
 'LoanAmount.205',
 'LoanAmount.208',
 'LoanAmount.209',
 'LoanAmount.210',
 'LoanAmount.211',
 'LoanAmount.214',
 'LoanAmount.216',
 'LoanAmount.218',
 'LoanAmount.225',
 'LoanAmount.239',
 'LoanAmount.242',
 'LoanAmount.244',
 'LoanAmount.250',
 'LoanAmount.253',
 'LoanAmount.255',
 'LoanAmount.258',
 'LoanAmount.259',
 'LoanAmount.260',
 'LoanAmount.265',
 'LoanAmount.275',
 'LoanAmount.286',
 'LoanAmount.290',
 'LoanAmount.292',
 'LoanAmount.304',
 'LoanAmount.308',
 'LoanAmount.311',
 'LoanAmount.312',
 'LoanAmount.320',
 'LoanAmount.349',
 'LoanAmount.350',
 'LoanAmount.360',
 'LoanAmount.370',
 'LoanAmount.376',
 'LoanAmount.400',
 'LoanAmount.405',
 'LoanAmount.436',
 'LoanAmount.480',
 'LoanAmount.495',
 'LoanAmount.496',
 'LoanAmount.500',
 'LoanAmount.570',
 'Loan_Amount_Term.12',
 'Loan_Amount_Term.36',
 'Loan_Amount_Term.60',
 'Loan_Amount_Term.84',
 'Loan_Amount_Term.120',
 'Loan_Amount_Term.180',
 'Loan_Amount_Term.240',
 'Loan_Amount_Term.300',
 'Loan_Amount_Term.360',
 'Loan_Amount_Term.480',
 'Credit_History.0',
 'Credit_History.1',
 'Property_Area.Rural',
 'Property_Area.Semiurban',
 'Property_Area.Urban']

In [101]:
print len(loans_data['Gender.'])

sum_nan = 0
for i in loans_data['Gender.']:  
    sum_nan += i
print sum_nan

sum_male = 0
for i in loans_data['Gender.Male']:  
    sum_male += i
print sum_male

print len(loans_data['Gender.Male'])

384
9
297
384